### ISSUE TITLE
api request

### ISSUE THREAD

**Issue by mysticvpn** [bobbyiliev/cloudflare-ddos-protection#1]
can this be firewall rule instead of security level under_attack? for example when cpu is above the normal level it will create firewall rule for get and post to have captcha/challenge mode? if yes can you help me to code it

**Comment by bobbyiliev** [comment]
Hi there,

At  the moment the script sets your status to “I’m under attack!” 

This will put up a JavaScript challenge which is far less annoying than CAPTCHAs.

In case that you need to have the firewall rule, you can change the curl request in the script to add a rule by using the[ Cloudflare API](https://api.cloudflare.com/). The logic in the script can remain the same, you will just need to change the curl request.
