### ISSUE TITLE
/home/$user/protection.sh: line 104: [: too many arguments

### ISSUE THREAD

**Issue by rpharrison** [bobbyiliev/cloudflare-ddos-protection#3]
Script is getting stuck while checking under_attack status.

**Comment by bobbyiliev** [comment]
Thanks for reporting this! I will look into it.

Probably your `curl` command fails due to some reason (Lines: https://github.com/bobbyiliev/cloudflare-ddos-protection/blob/main/protection.sh#L35-L38).

I will try to add better error handling for that.

**Comment by rpharrison** [comment]
Just wanted to update on this. Originally I only received a couple of emails like that from the script. 

I have been monitoring since and received the same message occasionally until today where I now got the following

/home/stephenl/protection.sh: line 104: [: ==: unary operator expected

**Comment by rpharrison** [comment]
I have tested adding extra []s to the code and so far it is correctly managing the security level. This PR should fix it.

**Comment by bobbyiliev** [comment]
Thanks for opening the PR! I've merged it now! Changes look great!
